#!/bin/bash

IMAGE=qiskit-flask-matplotlib-readerwriterlock
ZONE=us-central1-a
NAME=instance-1
PROJECT=can-i-break-rsa-now

# If an instance already exists, just connect. Otherwise, create first.
num_existing=$(gcloud compute instances list --project "${PROJECT}" --filter "name~${NAME}" | grep STATUS | wc -l)
if [ "$num_existing" -eq 0 ]; then
  gcloud beta compute --project=${PROJECT} instances create ${NAME} \
    --image-project=${PROJECT} \
    --boot-disk-device-name=${NAME} \
    --zone=${ZONE} \
    --machine-type=f1-micro \
    --subnet=default \
    --network-tier=PREMIUM \
    --maintenance-policy=MIGRATE \
    --service-account=748763487127-compute@developer.gserviceaccount.com \
    --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append \
    --tags=http-server \
    --image=${IMAGE} \
    --boot-disk-size=10GB \
    --boot-disk-type=pd-standard \
    --reservation-affinity=any
fi
gcloud compute --project "${PROJECT}" ssh --zone ${ZONE} ${NAME}
